language: java
dist: trusty
jdk:
  - openjdk8
env:
  - CODACY_PROJECT_TOKEN=a12d803109514a3dad9cfde2c54a68f9
script: ./gradlew check
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
